services:
  app:
    image: ghcr.io/xuchang200/web:latest
    ports:
      - "3000:3000"  # 单端口：Node 同时提供前端静态与 API
    env_file:
      - .env
    depends_on:
      - redis
      - db
    volumes:
      - uploads:/app/backend/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://127.0.0.1:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

  # PostgreSQL 数据库服务
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${DB_NAME:-gamedb}
      - POSTGRES_USER=${DB_USER:-user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app-network

  # 本地 Redis 服务
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis-password}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  uploads:

networks:
  app-network:
    driver: bridge