services:
  app:
    image: ghcr.io/xuchang200/web:latest
    ports:
      - "3000:3000"  # 单端口：Node 同时提供前端静态与 API
    env_file:
      - .env
    depends_on:
      - redis
      - db
    volumes:
      - uploads:/app/backend/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://127.0.0.1:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

  # MySQL 数据库服务
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DB_NAME:-gamedb}
      - MYSQL_USER=${DB_USER:-user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-password}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password

  # 本地 Redis 服务
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis-password}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mysql_data:
  redis_data:
  uploads:

networks:
  app-network:
    driver: bridge